### ISSUE TITLE
Линтер и CI

### ISSUE THREAD

**Issue by tshemsedinov** [vmkul/discordio#1]
Стиль хороший, даже очень, но eslint разве проходит? Можно добавить TravisCI, чтоб автобилдить, см. как я добавил сюда: https://github.com/HowProgrammingWorks/NodejsStarterKit/blob/master/.travis.yml

**Comment by vmkul** [comment]
> 
> 
> Стиль хороший, даже очень, но eslint разве проходит? Можно добавить TravisCI, чтоб автобилдить, см. как я добавил сюда: https://github.com/HowProgrammingWorks/NodejsStarterKit/blob/master/.travis.yml

Добавил TravisCI, build теперь проходит. Кофигурацию eslinta взял с node starter kit.

**Comment by tshemsedinov** [comment]
Отлично! Рекомендую делать в описании коммитов поля `Closes: <issueURL>` и `Refs: <issueURL>`, а так же делать feature-branch и PR из него в мастер, тогда github все ссылками связывает и в issue можно видеть какие коммиты и какие PR закрывают эту задачу, не нужно искать в истории.
